name: Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt -t ./package
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: deploy
        run: |
          cd package
          zip -r ../deploy.zip . 
          cd ..
          zip deploy.zip lambda_function.py queries.py shopify.py
          aws lambda update-function-code --function-name=tsh-one-piece-op12-price-updater --zip-file=fileb://deploy.zip